#!/usr/bin/python3
# ./dispatcher_test.py|grep RRR |sort|uniq> tt.txt
# ./dispatcher_test.py|grep YYY |sort|uniq> tt.txt

"""
lists the known functions

"""
allowed_signatures=[
b'delete atpiccom/chapter_',
b'delete atpiccom/chapter_section_',
b'delete atpiccom/entry_',
b'delete atpiccom/entry_line_',
b'delete atpiccom/news_',
b'delete atpiccom/product_',
b'delete atpiccom/translate_',
b'delete atpiccom/user_',
b'delete atpiccom/wiki_',
b'delete uname_buy_',
b'delete uname_comment_',
b'delete uname_friend_',
b'delete uname_gallery_',
b'delete uname_gallery_comment_',
b'delete uname_gallery_friend_',
b'delete uname_gallery_phrase_',
b'delete uname_gallery_pic_',
b'delete uname_gallery_pic_comment_',
b'delete uname_gallery_pic_face_',
b'delete uname_gallery_pic_path_',
b'delete uname_gallery_pic_phrase_',
b'delete uname_gallery_pic_tag_',
b'delete uname_gallery_tag_',
b'delete uname_payment_',
b'delete uname_pm_',
b'delete uname_pmsent_',
b'delete uname_sell_',
b'delete uname_wiki_',
b'get atpiccom/',
b'get atpiccom/admin/',
b'get atpiccom/audit/',
b'get atpiccom/captcha_',
b'get atpiccom/chapter_',
b'get atpiccom/chapter/',
b'get atpiccom/chapter_section_',
b'get atpiccom/chapter_section/',
b'get atpiccom/dragdrop.js/',
b'get atpiccom/du/',
b'get atpiccom/entry_',
b'get atpiccom/entry/',
b'get atpiccom/entry_line_',
b'get atpiccom/entry_line/',
b'get atpiccom/faq_',
b'get atpiccom/favicon.ico/',
b'get atpiccom/journal_',
b'get atpiccom/logout/',
b'get atpiccom/news_',
b'get atpiccom/news/',
b'get atpiccom/product_',
b'get atpiccom/product/',
b'get atpiccom/redirect/',
b'get atpiccom/robots.txt/',
b'get atpiccom/search_',
b'get atpiccom/search/',
b'get atpiccom/sitemap.xml/',
b'get atpiccom/translate_',
b'get atpiccom/translate/',
b'get atpiccom/user_',
b'get atpiccom/user/',
b'get atpiccom/wiki_',
b'get atpiccom/wiki_deadlink/',
b'get atpiccom/wiki_link/',
b'get atpiccom/wiki_linktothis/',
b'get atpiccom/wiki_revision_',
b'get atpiccom/wiki_revision/',
b'get delete atpiccom/chapter_',
b'get delete atpiccom/chapter_section_',
b'get delete atpiccom/entry_',
b'get delete atpiccom/entry_line_',
b'get delete atpiccom/news_',
b'get delete atpiccom/product_',
b'get delete atpiccom/translate_',
b'get delete atpiccom/user_',
b'get delete atpiccom/wiki_',
b'get delete uname_buy_',
b'get delete uname_comment_',
b'get delete uname_friend_',
b'get delete uname_gallery_',
b'get delete uname_gallery_comment_',
b'get delete uname_gallery_friend_',
b'get delete uname_gallery_phrase_',
b'get delete uname_gallery_pic_',
b'get delete uname_gallery_pic_comment_',
b'get delete uname_gallery_pic_face_',
b'get delete uname_gallery_pic_path_',
b'get delete uname_gallery_pic_phrase_',
b'get delete uname_gallery_pic_tag_',
b'get delete uname_gallery_tag_',
b'get delete uname_payment_',
b'get delete uname_pm_',
b'get delete uname_pmsent_',
b'get delete uname_sell_',
b'get delete uname_wiki_',
b'get legacy/',
b'get legacyobject_',
b'get legacyobject_id_',
b'get legacyobject_id_secret_',
b'get post atpiccom/chapter/',
b'get post atpiccom/chapter_section/',
b'get post atpiccom/entry/',
b'get post atpiccom/entry_line/',
b'get post atpiccom/login/',
b'get post atpiccom/news/',
b'get post atpiccom/product/',
b'get post atpiccom/translate/',
b'get post atpiccom/user/',
b'get post atpiccom/wiki_',
b'get post uname_buy/',
b'get post uname_comment/',
b'get post uname_friend/',
b'get post uname_gallery/',
b'get post uname_gallery_comment/',
b'get post uname_gallery_friend/',
b'get post uname_gallery_phrase/',
b'get post uname_gallery_pic/',
b'get post uname_gallery_pic_comment/',
b'get post uname_gallery_pic_face/',
b'get post uname_gallery_pic_path/',
b'get post uname_gallery_pic_phrase/',
b'get post uname_gallery_pic_tag/',
b'get post uname_gallery_pic_vote/',
b'get post uname_gallery_tag/',
b'get post uname_payment/',
b'get post uname_pm/',
b'get post uname_sell/',
b'get post uname_wiki_',
b'get put atpiccom/chapter_',
b'get put atpiccom/chapter_section_',
b'get put atpiccom/entry_',
b'get put atpiccom/entry_line_',
b'get put atpiccom/news_',
b'get put atpiccom/product_',
b'get put atpiccom/translate_',
b'get put atpiccom/user_',
b'get put atpiccom/wiki_',
b'get put uname_buy_',
b'get put uname_comment_',
b'get put uname_friend_',
b'get put uname_gallery_',
b'get put uname_gallery_comment_',
b'get put uname_gallery_friend_',
b'get put uname_gallery_phrase_',
b'get put uname_gallery_pic_',
b'get put uname_gallery_pic_comment_',
b'get put uname_gallery_pic_face_',
b'get put uname_gallery_pic_path_',
b'get put uname_gallery_pic_phrase_',
b'get put uname_gallery_pic_tag_',
b'get put uname_gallery_pic_vote_',
b'get put uname_gallery_tag_',
b'get put uname_payment_',
b'get put uname_sell_',
b'get put uname_wiki_',
b'get selldns_',
b'get selldns_1x1.gif/',
b'get selldns_audit/',
b'get selldns_blog_',
b'get selldns_blognav_',
b'get selldns_blogsearch_',
b'get selldns_contact/',
b'get selldns_favicon.ico/',
b'get selldns_logout/',
b'get selldns_robots.txt/',
b'get selldns_search/',
b'get selldns_sitemap.xml/',
b'get selldns_tree_',
b'get selldns_treenav_',
b'get selldns_treesearch_',
b'get selldns_vtree_',
b'get selldns_vtreenav_',
b'get selldns_vtreesearch_',
b'get uname_',
b'get uname_audit/',
b'get uname_buy_',
b'get uname_buy/',
b'get uname_cart/',
b'get uname_blog_',
b'get uname_blognav_',
b'get uname_blogsearch_',
b'get uname_comment_',
b'get uname_comment/',
b'get uname_contact/',
b'get uname_dragdrop.js/',
b'get uname_du/',
b'get uname_friend_',
b'get uname_friend/',
b'get uname_g/',
b'get uname_gallery_',
b'get uname_gallery/',
b'get uname_gallery_below/',
b'get uname_gallery_comment_',
b'get uname_gallery_comment/',
b'get uname_gallery_friend_',
b'get uname_gallery_friend/',
b'get uname_gallery_g/',
b'get uname_gallery_gallery/',
b'get uname_gallery_path/',
b'get uname_gallery_phrase_',
b'get uname_gallery_phrase/',
b'get uname_gallery_pic_',
b'get uname_gallery_pic/',
b'get uname_gallery_pic_comment_',
b'get uname_gallery_pic_comment/',
b'get uname_gallery_pic_exif/',
b'get uname_gallery_pic_face/',
b'get uname_gallery_pic_gallery/',
b'get uname_gallery_pic_path_',
b'get uname_gallery_pic_path/',
b'get uname_gallery_pic_phrase_',
b'get uname_gallery_pic_phrase/',
b'get uname_gallery_pic_sizeb/',
b'get uname_gallery_pic_tag_',
b'get uname_gallery_pic_tag/',
b'get uname_gallery_pic_vote_',
b'get uname_gallery_tag_',
b'get uname_gallery_tag/',
b'get uname_gallery_treenav/',
b'get uname_geo_',
b'get uname_geonav_',
b'get uname_geosearch_',
b'get uname_journal_',
b'get uname_payment_',
b'get uname_payment/',
b'get uname_pm_',
b'get uname_pm/',
b'get uname_pmsent_',
b'get uname_pmsent/',
b'get uname_preferences/',
b'get uname_robots.txt/',
b'get uname_search/',
b'get uname_sell_',
b'get uname_sell/',
b'get uname_tree_',
b'get uname_treenav_',
b'get uname_treesearch_',
b'get uname_vtree_',
b'get uname_vtreenav_',
b'get uname_vtreesearch_',
b'get uname_wiki_',
b'get uname_wiki_deadlink/',
b'get uname_wiki_link/',
b'get uname_wiki_linktothis/',
b'get uname_wiki_picture/',
b'get uname_wiki_revision_',
b'get uname_wiki_revision/',
b'post atpiccom/chapter/',
b'post atpiccom/chapter_section/',
b'post atpiccom/entry/',
b'post atpiccom/entry_line/',
b'post atpiccom/login/',
b'post atpiccom/news/',
b'post atpiccom/product/',
b'post atpiccom/translate/',
b'post atpiccom/user/',
b'post atpiccom/wiki_',
b'post delete atpiccom/chapter_',
b'post delete atpiccom/chapter_section_',
b'post delete atpiccom/entry_',
b'post delete atpiccom/entry_line_',
b'post delete atpiccom/news_',
b'post delete atpiccom/product_',
b'post delete atpiccom/translate_',
b'post delete atpiccom/user_',
b'post delete atpiccom/wiki_',
b'post delete uname_buy_',
b'post delete uname_comment_',
b'post delete uname_friend_',
b'post delete uname_gallery_',
b'post delete uname_gallery_comment_',
b'post delete uname_gallery_friend_',
b'post delete uname_gallery_phrase_',
b'post delete uname_gallery_pic_',
b'post delete uname_gallery_pic_comment_',
b'post delete uname_gallery_pic_face_',
b'post delete uname_gallery_pic_path_',
b'post delete uname_gallery_pic_phrase_',
b'post delete uname_gallery_pic_tag_',
b'post delete uname_gallery_tag_',
b'post delete uname_payment_',
b'post delete uname_pm_',
b'post delete uname_pmsent_',
b'post delete uname_sell_',
b'post delete uname_wiki_',
b'post post atpiccom/chapter/',
b'post post atpiccom/chapter_section/',
b'post post atpiccom/entry/',
b'post post atpiccom/entry_line/',
b'post post atpiccom/news/',
b'post post atpiccom/product/',
b'post post atpiccom/translate/',
b'post post atpiccom/user/',
b'post post atpiccom/wiki_',
b'post post uname_buy/',
b'post post uname_comment/',
b'post post uname_friend/',
b'post post uname_gallery/',
b'post post uname_gallery_comment/',
b'post post uname_gallery_friend/',
b'post post uname_gallery_phrase/',
b'post post uname_gallery_pic_',
b'post post uname_gallery_pic/',
b'post post uname_gallery_pic_comment/',
b'post post uname_gallery_pic_face/',
b'post post uname_gallery_pic_path/',
b'post post uname_gallery_pic_phrase/',
b'post post uname_gallery_pic_tag/',
b'post post uname_gallery_pic_vote/',
b'post post uname_gallery_tag/',
b'post post uname_payment/',
b'post post uname_pm/',
b'post post uname_sell/',
b'post post uname_wiki_',
b'post put atpiccom/chapter_',
b'post put atpiccom/chapter_section_',
b'post put atpiccom/entry_',
b'post put atpiccom/entry_line_',
b'post put atpiccom/news_',
b'post put atpiccom/product_',
b'post put atpiccom/translate_',
b'post put atpiccom/user_',
b'post put atpiccom/wiki_',
b'post put uname_buy_',
b'post put uname_comment_',
b'post put uname_friend_',
b'post put uname_gallery_',
b'post put uname_gallery_comment_',
b'post put uname_gallery_friend_',
b'post put uname_gallery_phrase_',
b'post put uname_gallery_pic_',
b'post put uname_gallery_pic_comment_',
b'post put uname_gallery_pic_face_',
b'post put uname_gallery_pic_path_',
b'post put uname_gallery_pic_phrase_',
b'post put uname_gallery_pic_tag_',
b'post put uname_gallery_pic_vote_',
b'post put uname_gallery_secret/',
b'post put uname_gallery_tag_',
b'post put uname_payment_',
b'post put uname_sell_',
b'post put uname_wiki_',
b'post uname_buy/',
b'post uname_comment/',
b'post uname_du/',
b'post uname_friend/',
b'post uname_ftp/',
b'post uname_gallery/',
b'post uname_gallery_comment/',
b'post uname_gallery_friend/',
b'post uname_gallery_phrase/',
b'post uname_gallery_pic/',
b'post uname_gallery_pic_chown/',
b'post uname_gallery_pic_comment/',
b'post uname_gallery_pic_face/',
b'post uname_gallery_pic_path/',
b'post uname_gallery_pic_phrase/',
b'post uname_gallery_pic_rotate/',
b'post uname_gallery_pic_tag/',
b'post uname_gallery_pic_thumbnail/',
b'post uname_gallery_pic_vote/',
b'post uname_gallery_tag/',
b'post uname_payment/',
b'post uname_pm/',
b'post uname_preferences/',
b'post uname_quota/',
b'post uname_sell/',
b'post uname_wiki_',
b'put atpiccom/chapter_',
b'put atpiccom/chapter_section_',
b'put atpiccom/entry_',
b'put atpiccom/entry_line_',
b'put atpiccom/news_',
b'put atpiccom/product_',
b'put atpiccom/translate_',
b'put atpiccom/user_',
b'put atpiccom/wiki_',
b'put uname_buy_',
b'put uname_comment_',
b'put uname_friend_',
b'put uname_gallery_',
b'put uname_gallery_comment_',
b'put uname_gallery_friend_',
b'put uname_gallery_gallery_',
b'put uname_gallery_phrase_',
b'put uname_gallery_pic_',
b'put uname_gallery_pic_comment_',
b'put uname_gallery_pic_face_',
b'put uname_gallery_pic_gallery_',
b'put uname_gallery_pic_path_',
b'put uname_gallery_pic_phrase_',
b'put uname_gallery_pic_tag_',
b'put uname_gallery_pic_vote_',
b'put uname_gallery_tag_',
b'put uname_payment_',
b'put uname_sell_',
b'put uname_wiki_',
b'get post atpiccom/forgot/',
b'post atpiccom/forgot/',
b'get post atpiccom/reset_',
b'post atpiccom/reset_',
]

actions_list=[b'get',b'post',b'put',b'delete']

