"""
Could store in SQL
on file system with date? but then need a gallery
or special filesystem
alex.atpic.com/avatar.png
or alex.avatar.atpic.com/avatar.png NO!
same for favicon.ico
favicon needs to be on the same host name

Rule: no date in URL, so not possible to use a date based filesystem

or in a gallery with lookup on name to get the date???

Could use redirect at proxy level?

alex.atpic.com/art/
atpic.com/art/

/atpicart/al/alex/favicon.ico
/atpicart/al/alex/avatar.png
/atpicart/al/alex/art/title1.png

or in SQL, or in REDIS? (too much memory?)


problem: sync with rsync?
yes, as it is small?

or make a elasticsearch search on the user id for the name 'avatar.png'
and 'favicon.ico'
Problem: it you have may requests generated by the same page: perf hit...
needs a very fast file system like (maps path to local FS)
or SQL (but can be big)

or make a SQL search in user's pics for name 'favicon.ico'
cahce the result to redis and stream the file from disk
adavantages: normal repo in normal gal;leries
just yet another fuse wrapper

"""
